name: Perform tests
on:
  workflow_run:
    workflows: ["Setup Environment"]
    branches: [master]
    types:
      - completed
      - requested
jobs:
  chromatic:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Yarn install
        run: yarn install

      - name: Chromatic run
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.chromatic }}
          token: ${{ secrets.GITHUB_TOKEN }}
