name: Release bento
on: push
jobs:
  release:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: '12.x'
          registry-url: https://registry.npmjs.org
          scope: '@xstate @sanity'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test:ci
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
